/**
 * This code was generated by Builder.io.
 */
import Image from "next/image";
import React from "react";

 const Navbar = () => {
  return (
    <div className="flex flex-row w-full max-md:justify-start max-md:items-start max-sm:items-center">
      <div className="flex relative flex-row gap-5 justify-between items-center self-stretch my-3 w-full">
        <div className="flex relative flex-row self-stretch grow-[1.1674179080885916] max-md:items-center max-md:my-auto max-md:mr-auto max-md:w-full max-sm:justify-start">
          {/* <Image
          width={ 120}
          height={120}
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F1bc483cb64c5410099c519ed6e11be05"
            className="box-border object-contain overflow-hidden shrink-0 mx-auto w-full max-h-12 pointer-events-auto aspect-[0.52] max-w-[90px] min-h-[20px] min-w-[20px] max-md:grow max-md:mr-auto max-md:w-auto max-sm:mr-auto max-sm:max-h-[42px] max-sm:max-w-[53px] max-sm:min-w-[42px]"
            alt="image"
         /> */}
          <div className="flex relative flex-col mt-4 grow-[3.1608208817763215]  max-md:flex-row max-md:mr-auto max-sm:hidden">
            <div className="flex relative flex-row gap-4 justify-start self-stretch max-md:justify-center">
              <div className="box-border relative shrink-0 pointer-events-auto">
                <p>Home</p>
              </div>
              <div className="box-border relative shrink-0 pointer-events-auto">
                <p>
                  <a href="http://localhost:3000/about">About</a>
                </p>
              </div>
              <div className="box-border relative shrink-0 ml-0.5 pointer-events-auto max-md:mx-0.5">
                <p>
                  <a href="http://localhost:3000/contact">Contact</a>
                </p>
              </div>
              <div className="box-border relative shrink-0 ml-3 pointer-events-auto max-md:mx-2.5">
                <p>Projects</p>
              </div>
            </div>
          </div>
        </div>
        <div className="flex relative flex-row mt-px ml-auto w-auto grow-0 max-md:hidden max-sm:hidden">
          <button
            className="box-border relative shrink-0 p-3 mr-4 ml-auto text-center text-black rounded appearance-none cursor-pointer grow-0"
            // openLinkInNewTab={false}
          >
            Request a demo
          </button>
          <div className="box-border flex relative flex-col shrink-0 my-auto w-0.5 h-8 bg-stone-300" />
          <div className="flex relative flex-row gap-4 ml-4">
            <button
              // href="#"
              className="box-border relative shrink-0 p-3 text-center text-black rounded appearance-none cursor-pointer grow-0"
              // openLinkInNewTab={false}
            >
              Login
            </button>
            <button
              className="box-border relative shrink-0 p-3 text-center rounded appearance-none cursor-pointer bg-[black] grow-0 text-[white]"
              // openLinkInNewTab={false}
            >
              Get Product
            </button>
          </div>
        </div>
      </div>
     
    </div>
  );
}


export default Navbar