/**
 * This code was generated by Builder.io.
 */
import Image from "next/image";
import  React from "react";

const RecentProjectsSection= () => {
  return (
    <div
      className="box-border flex relative flex-col shrink-0 p-5 min-h-[100px] max-sm:mt-52"
     
      // lazyLoad={false}
    >
      <section className="box-border flex relative flex-col grow shrink-0 self-stretch p-5 mx-auto w-full max-w-[1200px] min-h-[100px] max-sm:mt-52">
        <div className="box-border relative shrink-0 mt-24 h-auto text-5xl font-semibold text-center">
          <p>Recent projects</p>
        </div>
        <div className="box-border flex relative flex-row flex-wrap shrink-0 gap-7 justify-center self-center mt-10 w-full max-w-[973px] max-md:w-full max-md:max-w-[450px] max-sm:flex max-sm:flex-col max-sm:items-center">
          <a
            href="https://www.builder.io/c/docs/integrating-builder-pages#creating-a-builder-page"
            target="_blank"
            className="box-border flex overflow-hidden relative flex-col shrink-0 justify-between w-full cursor-pointer pointer-events-auto max-sm:items-center max-sm:max-w-[300px]"
          />
          <a
            href="https://www.builder.io/c/docs/custom-components-intro"
            target="_blank"
            className="box-border flex overflow-hidden relative flex-col shrink-0 justify-between cursor-pointer pointer-events-auto max-w-[48%] max-md:w-full max-md:max-w-full max-sm:items-center max-sm:max-w-[300px]"
          >
            <div className="box-border flex overflow-hidden relative flex-col shrink-0 pb-5 rounded-lg border border-black border-solid">
              <div className="box-border flex relative flex-col shrink-0 bg-slate-900">
                <Image
                width={2040}
                height={120}
                alt="image"
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F5a4c2bdfff2049c09a9b7dbcc036a263?width=4000 4000w "
                  className="box-border object-cover overflow-hidden shrink-0 w-full aspect-[3.3] min-h-[20px] min-w-[20px]"
                />
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-2.5 mb-2.5 h-auto font-semibold text-center text-black">
                <p>Register your Next components </p>
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-0 h-auto text-xs text-center text-black max-sm:text-center">
                <p>
                  Register your Next.js components in Builder. You can drag and
                  drop any custom component from the Visual Editor onto a page.
                </p>
              </div>
            </div>
          </a>
          <a
            href="https://www.builder.io/c/blueprints"
            target="_blank"
            className="box-border flex overflow-hidden relative flex-col shrink-0 justify-between pb-1 rounded-lg border border-black border-solid cursor-pointer pointer-events-auto max-w-[48%] max-md:w-full max-md:max-w-full max-sm:items-center max-sm:max-w-[300px]"
          >
            <div className="box-border flex relative flex-col shrink-0">
              <div className="box-border flex relative flex-col shrink-0 justify-center items-center px-2.5 pt-2.5 pb-20 mb-0.5 bg-zinc-900">
                <Image
                width={2040}
                height={120}
                alt="image"
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F74cceb58eae948e4b1edcc930a7c23b9?format=webp&width=4000 4000w "
                  className="box-border object-cover overflow-hidden shrink-0 w-full aspect-[3.02] max-w-[170px] min-h-[20px] min-w-[20px]"
                />
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-2.5 mb-2.5 h-auto font-semibold text-center text-black">
                <p>Integrate common use cases</p>
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-0 h-auto text-xs text-center text-black max-sm:text-center">
                <p>
                  Reference how you can use Builder for your blog, eCommerce
                  product listings, or for your entire site.
                </p>
              </div>
            </div>
          </a>
          <a
            href="https://www.builder.io/c/docs/ui-ve-tour"
            target="_blank"
            className="box-border flex overflow-hidden relative flex-col shrink-0 justify-between cursor-pointer pointer-events-auto max-w-[48%] max-md:w-full max-md:max-w-full max-sm:items-center max-sm:max-w-[300px]"
          >
            <div className="box-border flex overflow-hidden relative flex-col shrink-0 pb-5 h-full rounded-lg border border-black border-solid pointer-events-auto">
              <Image
              width={2040}
              height={120}
              alt="image"
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F8195e5670c27459fb5231c7e24d6de58?width=4000 4000w"
                className="box-border object-cover overflow-hidden shrink-0 w-full aspect-[2.22] min-h-[20px] min-w-[20px]"
              />
              <div className="box-border relative shrink-0 px-2.5 mt-2.5 mb-2.5 h-auto font-semibold text-center text-black">
                <p>Tour the Visual Editor </p>
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-0 h-auto text-xs text-center text-black max-sm:text-center">
                <p>
                  Check out the UI of the Visual Editor and compose complex
                  layouts without writing any code.
                </p>
              </div>
            </div>
          </a>
          <a
            href="https://www.builder.io/c/docs/block-types"
            target="_blank"
            className="box-border flex overflow-hidden relative flex-col shrink-0 justify-between cursor-pointer pointer-events-auto max-w-[48%] max-md:w-full max-md:max-w-full max-sm:items-center max-sm:max-w-[300px]"
          >
            <div className="box-border flex overflow-hidden relative flex-col shrink-0 pb-5 rounded-lg border border-black border-solid pointer-events-auto">
              <Image
              width={2040}
              height={120}
              alt="image"
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2Fcda9ac8a8433413b9d9c3606812cabc9?width=4000 4000w "
                className="box-border object-cover overflow-hidden shrink-0 w-full aspect-[2.22] min-h-[20px] min-w-[20px]"
              />
              <div className="box-border relative shrink-0 px-2.5 mt-2.5 mb-2.5 h-auto font-semibold text-center text-black">
                <p>Learn the building blocks</p>
              </div>
              <div className="box-border relative shrink-0 px-2.5 mt-0 h-auto text-xs text-center text-black max-sm:text-center">
                <p>
                  Creating content in Builder uses a flexible toolset of no-code
                  blocks that you can use to create almost anything.
                </p>
              </div>
            </div>
          </a>
        </div>
        <a
          href="https://portfolio-next-git-main-abduganis-projects.vercel.app/"
            className="box-border flex relative flex-col shrink-0 items-center pb-8 pl-px mt-5 ml-24 h-auto rounded-lg border border-solid cursor-pointer pointer-events-auto border-neutral-600 max-w-[474px] max-md:ml-14 max-md:max-w-[460px] max-sm:-ml-0.5"
   >
          <Image
         width={2040}
         height={120}
          
          alt="image"
            loading="lazy"
            src={"https://i.pinimg.com/564x/5b/50/ca/5b50ca80f27dee00adb6727d55cef0f6.jpg?format=webp&width=4000 4000w"}
            className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[-14.88] min-h-[250px] min-w-[20px] max-sm:min-h-[150px]"
          />
          <div className="box-border relative shrink-0 mt-5 h-auto text-xl font-semibold text-center pointer-events-auto">
            <p>All in One</p>
          </div>
        </a>
      </section>
    </div>
  );
}

export default RecentProjectsSection